steps:
  - id: "Build image"
    name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}
      - --cache=true
    env:
      - "DOCKER_BUILDKIT=1"

  - id: "Build Cypress"
    name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --dockerfile=./cypress/Dockerfile
      - --destination=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}_cypress
      - --cache=true
    env:
      - "DOCKER_BUILDKIT=1"
    waitFor: ["-"]

  - id: "Deploy revision with tag"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--platform",
        "managed",
        "--region",
        "${_REGION}",
        "--image",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}",
        "--tag",
        "pr-${_PR_NUMBER}",
        "--no-traffic",
      ]

substitutions:
  _REPOSITORY_NAME: simonandrews-ca
  _SERVICE_NAME: simonandrews-ca
  _REGION: europe-west1

options:
  dynamicSubstitutions: true
