version: "3.5"
services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/app:delegated
      - /app/node_modules/
    ports:
      - 3000:3000
    networks:
      - default
    profiles:
      - dev

  deps:
    build:
      context: .
      target: deps-dev
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /src/node_modules/
    profiles:
      - deps

  production:
    build:
      context: .
    ports:
      - 3001:3000
    profiles:
      - production
      - e2e
    networks:
      - default

  cypress:
    build:
      context: ./cypress
    environment:
      - CYPRESS_baseUrl=http://production:3000
    volumes:
      - ./cypress:/app
      - /app/node_modules/
    profiles:
      - e2e
    networks:
      - default
